graph TD
J[Disputed] --> A
A[Vote phase scheduled at request block] --> C[Vote Phase]
C --> D[Aggregation Phase]
D --> E[Appeal Phase]
E -. up to three appeals .-> A 
E -. fourth appeal .->  F[Global Dispute]
E -. phase ends with no appeal .-> L
F --> L[Resolved]